name: Deploy debug web part to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Create web part from Yeoman generator
        run: npx -p yo -p @microsoft/generator-sharepoint@1.15.2 --yes -- yo @microsoft/sharepoint --skip-install --solution-name="webpart" --component-type "webpart" --component-description "HelloWorld description" --component-name "HelloWorld" --framework "react" --package-manager "npm" --skip-feature-deployment

      - name: Install dependencies
        run: npm install
        working-directory: webpart

      - name: Run bundle
        run: npm run build
        working-directory: webpart
      
      - name: Copy webpart artifacts
        run: |
          mkdir artifacts
          cp webpart/README.md artifacts
          cp -r webpart/dist artifacts/dist
          cp -r webpart/dist artifacts/lib
          cp -r webpart/temp artifacts/temp

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'https://localhost:4321/dist/'
          replace: 'https://cwparsons.ca/${{ github.event.repository.name }}/dist/'
          regex: false
          include: 'artifacts/**'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./artifacts

  # Deployment job
  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1