name: Deploy debug web part to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run bundle
        run: npm run build

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "https://localhost:4321/"
          replace: "https://cwparsons.ca/${{ github.event.repository.name }}"
          regex: false
          include: temp/**/*
      
      - name: Copy artifacts
        run: |
          mkdir artifacts
          cp README.md artifacts
          cp -r dist artifacts/dist
          cp -r dist artifacts/lib
          cp -r temp artifacts/temp

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./artifacts

  # Deployment job
  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1